title: Jacob Baker-Kretzmar
email: jacob@bakerkretzmar.ca
description: A website for Jacob Baker-Kretzmar.
url: "https://bakerkretzmar.ca"
twitter_username: jacobbakr
github_username:  bakerkretzmar

manifest:
  name: Jacob Baker-Kretzmar
  short_name: bakerkretzmar.ca
  lang: en-CA
  background_color: "#001680"
  display: browser
  description: Website of Jacob Baker-Kretzmar, web designer and developer.

# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       image: icon.png

# google_site_verification:

markdown: kramdown
kramdown:
  auto_ids: false
gems:
  - jekyll-assets
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-extlinks
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
  - s3_website.yml
permalink: pretty
assets:
  sources:
    - "_assets/fonts"
  assets:
    - "sw.js"
  autoprefixer:
    browsers: ["last 3 versions","> 0.01%"]
  features:
    liquid: true
  prefix: ""
# extlinks:
  # attributes: {target: _blank}
