[build]
    command = "npm run prod"
    publish = "public"
    environment = { PHP_VERSION = "7.4", NODE_VERSION = "14" }

[[headers]]
    for = "/*"
    [headers.values]
        Permissions-Policy = "interest-cohort=()"

[[redirects]]
    from = "/t"
    to = "https://twitter.com/bakerkretzmar"

[[redirects]]
    from = "/twitter"
    to = "https://twitter.com/bakerkretzmar"

[[redirects]]
    from = "/g"
    to = "https://github.com/bakerkretzmar"

[[redirects]]
    from = "/github"
    to = "https://github.com/bakerkretzmar"
